INSERT INTO users (username, password, role)
VALUES
  ('TEST_USER_1', 'I AM A PASSWORD', 'ROLE_TEST'),
  ('TEST_USER_2', 'I AM A PASSWORD', 'ROLE_TEST'),
  ('TEST_USER_3', 'I AM A PASSWORD', 'ROLE_TEST'),
  ('TEST_USER_4', 'I AM A PASSWORD', 'ROLE_TEST'),
  ('TEST_USER_5', 'I AM A PASSWORD', 'ROLE_TEST'),
  ('TEST_USER_6', 'I AM A PASSWORD', 'ROLE_TEST'),
  ('TEST_USER_7', 'I AM A PASSWORD', 'ROLE_TEST'),
  ('TEST_USER_8', 'I AM A PASSWORD', 'ROLE_TEST'),
  ('TEST_USER_9', 'I AM A PASSWORD', 'ROLE_TEST'),
  ('TEST_USER_10', 'I AM A PASSWORD', 'ROLE_TEST')
 ;


